// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZBbFcFZtNenbi-K33aaIbgOpLGHBdH0',
    appId: '1:403502148741:web:25e002a8c33e30623ccdec',
    messagingSenderId: '403502148741',
    projectId: 'cardify-b8c2b',
    authDomain: 'cardify-b8c2b.firebaseapp.com',
    storageBucket: 'cardify-b8c2b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWZBbFcFZtNenbi-K33aaIbgOpLGHBdH0',
    appId: '1:403502148741:android:25e002a8c33e30623ccdec',
    messagingSenderId: '403502148741',
    projectId: 'cardify-b8c2b',
    storageBucket: 'cardify-b8c2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZBbFcFZtNenbi-K33aaIbgOpLGHBdH0',
    appId: '1:403502148741:ios:25e002a8c33e30623ccdec',
    messagingSenderId: '403502148741',
    projectId: 'cardify-b8c2b',
    storageBucket: 'cardify-b8c2b.firebasestorage.app',
    iosBundleId: 'com.example.business_card_reader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZBbFcFZtNenbi-K33aaIbgOpLGHBdH0',
    appId: '1:403502148741:ios:25e002a8c33e30623ccdec',
    messagingSenderId: '403502148741',
    projectId: 'cardify-b8c2b',
    storageBucket: 'cardify-b8c2b.firebasestorage.app',
    iosBundleId: 'com.example.business_card_reader',
  );
}